### ISSUE TITLE
Clarification on interaction between System Under Test and Initial State

### ISSUE THREAD

**Issue by jamesd** [leanovate/gopter#5]
Looking for clarification on how a complex state is supposed to be handled along with creation and destruction of a SUT.

For example, testing a circular buffer you could have a container/list mirror the contents of the circular buffer to verify behaviour in a state structure. However, I do not see how to correlate re-initializing the state when the SUT is destroyed and recreated. Is there something I am missing?

**Comment by untoldwind** [comment]
Hi,
I freely admit that the commands package is the best adaption I could find to the version in ScalaCheck, so there still might be something missing.

I think your problem is that you do not know what specific kind of `command.State` was generated via `GenInitialState` when the `NewSystemUnderTest` function is called.

Would it help if I refactor `NewSystemUnderTest()` to `NewSystemUnderTest(initialState commands.State)`?

**Comment by jamesd** [comment]
Yes, I believe that is what is needed. Thanks for jumping on this quickly.

**Comment by untoldwind** [comment]
While I was on it I also found some minor issues/inconveniences in the commands package. Here's the excerpt from the changelog:

- `commands.Command.PostCondition` was called with the state before running the command. It makes
  much more sense to first do `commands.Command.NextState` and then `commands.Command.PostCondition`
- `commands.Commands.NewSystemUnderTest` now takes has an argument `initialState commands.State` to
  allow implementators to create/bootstrap a system under test based on an arbitrary initial state.
  So far examples were just using a constant initial state ... which is a bit boring.
- Fixed: Actually use `commands.Commands.InitialPreCondition` as sieve for
  `commands.Commands.GenInitialState`

**Comment by untoldwind** [comment]
... I think this should be closed now

**Comment by jamesd** [comment]
I'm still having issues getting the command-based testing to work. A simple circular buffer example is how I have been trying to work out how to use gopter's command-based testing (see https://github.com/jamesd/circular-buffer). Hopefully you'll be able to show me where I am using the package incorrectly.

Once this is working, I think it would make a good example to add.

Thanks again.

**Comment by untoldwind** [comment]
Ok, will take a look.
Seems to be a much better example than the silly counter

**Comment by untoldwind** [comment]
Ok, I added a fixed version of your example:
https://github.com/leanovate/gopter/blob/master/commands/example_circularqueue_test.go

As usually the problem is quite simple and hard at the same time: Since this package is a ripoff from ScalaCheck the `commands.State` is supposed to be immutable. For scala this is almost natural (using case classes) ... for go, no so much. So I'll have to figure out a better solution for that.

Anyhow: I separated the state from the commands (i.e. there is now a cbState and cbCommands), used slices instead of list.List and ensured that NextState always creates a new cbState (leaving the previous untouched) ... and then I works just like it should.

**Comment by jamesd** [comment]
Ah, immutable state is what I was missing. Thanks for the quick turn around on this.

**Comment by untoldwind** [comment]
It's on of the little implicit assumption that just got lost in translation, but make perfectly sense when thinking it over more carefully.

The underlying issue was about re-runability. I.e. when generating a sequence of commands I have to be able to apply them to the same initial state several times.

I did some internal refactoring and elaborated on your example a bit further. Now that state can be mutable, provided that the result of the `GenInitialState` generator is reproducable. I.e. if it gets the same `gopter.GenParameters` it has to generate the same State every time.

Unluckily `gen.ConstOf(<pointer to something that might be change>)` does not satisfy this condition, so I added an explicit warning in the documentation.

**Comment by untoldwind** [comment]
I think the example (https://github.com/leanovate/gopter/blob/master/commands/example_circularqueue_test.go) now covers the essentials.
Just give me a ping if you are ok with it.

**Comment by jamesd** [comment]
Since this is an example, I'd like to see some comments as to why getPutCommand needs an explicit shrinker as it is not obvious to me (e.g., the other gen*Command constructs do not have one explicitly stated).

Line 151 comment is not correct.

**Comment by untoldwind** [comment]
Thanks for the feedback. I added some explanations that hopefully clarify things a bit.

**Comment by jamesd** [comment]
Ok, so while the shrinker is not technically needed in this case, it shows how to use it when generating commands. For an example, that is useful.

Thanks.

**Comment by untoldwind** [comment]
Well yes, shrinkers are not required if just stress-testing a chunk of code, i.e. "just" detect if there are unknown edge-cases. Shrinkers are useful to find the actual edge of these edge-cases (or at least one of them).

That said: IMHO the example is still slightly incomplete since the initial state might be also shrinkable (in this case: find the minimal sequence of commands AND minimal queue size to produce an error).
Unluckily the implementation is far more complex than expected, so I'll leave this open for now.
